name: Build and Push to Docker Hub and deploy to EC2

on:
  push:
    branches: [ main ]
    paths:
      - '**/Dockerfile'
      - '**/docker-compose*.yml'
      - '.github/workflows/docker-publish.yml'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push socket_server
      uses: docker/build-push-action@v4
      with:
        context: ./socket_server
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/scmlite-socket-server:${{ github.run_number }}
          ${{ env.DOCKERHUB_USERNAME }}/scmlite-socket-server:latest

    - name: Build and push producer
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./producer/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/scmlite-producer:${{ github.run_number }}
          ${{ env.DOCKERHUB_USERNAME }}/scmlite-producer:latest

    - name: Build and push consumer
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./consumer/Dockerfile
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/scmlite-consumer:${{ github.run_number }}
          ${{ env.DOCKERHUB_USERNAME }}/scmlite-consumer:latest

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./backend/Dockerfile
        push: true
        build-args: |
          VITE_API_URL= http://${{ secrets.SERVER_HOST }}:8000
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/scmlite-backend:${{ github.run_number }}
          ${{ env.DOCKERHUB_USERNAME }}/scmlite-backend:latest

  # deploy-ec2:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #     - name: Deploy to EC2 via SSH and docker-compose
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_SSH_USER }}
  #         key: ${{ secrets.SERVER_SSH_KEY }}
  #         port: ${{ secrets.EC2_PORT || '22' }}
  #         script: |
  #           set -e
  #           cd /opt/scmlite
  #           docker-compose pull
  #           docker-compose up -d --remove-orphans
